name: helpers
description: Helpers is a tool that allows you to convert repetitive and tedious statements into easy-to-read and intuitive statements.
version: 1.2.0
homepage: https://github.com/seel-channel/helpers

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.17.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
